### ISSUE TITLE
Sampling drift issue

### ISSUE THREAD

**Issue by GYDDHPY** [JiYuanFeng/DDP#4]
Thank you for your great work and sharing the code.

You mentioned sampling drift problem in your paper. It seems you proposed 'self-aligned denoising' method to solve the problem. However, I didn't find it in your released code. Can you tell me where it is? Or the 'self-aligned denoising' method is just to verify the sampling drift problem but not inclueded in the released code?

Looking forward to your reply.

**Comment by czczup** [comment]
Hi, GTDDHPY. Code for self-aligned denoising has been released.

**Comment by GYDDHPY** [comment]
Thank you for sharing the related code. 

Best wishes.
