### ISSUE TITLE
BEV code release

### ISSUE THREAD

**Issue by twoDragonBear** [JiYuanFeng/DDP#8]
Hi! @JiYuanFeng  @czczup 
Thanks for you great work!
ARE there plans to release the code of bev segmentation?

**Comment by czczup** [comment]
Hi @twoDragonBear, we plan to release the bev code in the next 1-2 weeks.

**Comment by twoDragonBear** [comment]
Looking forward to the BEV code, and congratulations on being accepted by ICCV!

**Comment by JiYuanFeng** [comment]
hi, @twoDragonBear, we have released the part of the bev seg. If you have any questions please feel free to let us know.
